// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkShop1.Data;

#nullable disable

namespace WorkShop1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223144239_EnrollmentFix")]
    partial class EnrollmentFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkShop1.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("FirstTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Programme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SecondTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FirstTeacherId");

                    b.HasIndex("SecondTeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 6,
                            FirstTeacherId = 1,
                            Programme = "IT",
                            SecondTeacherId = 3,
                            Semester = 3,
                            Title = "Databases"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 6,
                            FirstTeacherId = 2,
                            Programme = "IT",
                            SecondTeacherId = 4,
                            Semester = 4,
                            Title = "Web Programming"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 6,
                            FirstTeacherId = 1,
                            Programme = "SE",
                            SecondTeacherId = 5,
                            Semester = 5,
                            Title = "Software Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 5,
                            FirstTeacherId = 4,
                            Programme = "IT",
                            SecondTeacherId = 2,
                            Semester = 6,
                            Title = "Computer Networks"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 6,
                            FirstTeacherId = 3,
                            Programme = "SE",
                            SecondTeacherId = 1,
                            Semester = 5,
                            Title = "Operating Systems"
                        });
                });

            modelBuilder.Entity("WorkShop1.Models.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AdditionalPoints")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectPoints")
                        .HasColumnType("int");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Semester")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SeminarPoints")
                        .HasColumnType("int");

                    b.Property<string>("SeminarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CourseId = 1,
                            Grade = 9,
                            Semester = "Fall",
                            StudentId = 1L,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2L,
                            CourseId = 1,
                            Grade = 8,
                            Semester = "Fall",
                            StudentId = 2L,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3L,
                            CourseId = 2,
                            Grade = 10,
                            Semester = "Spring",
                            StudentId = 3L,
                            Year = 2024
                        },
                        new
                        {
                            Id = 4L,
                            CourseId = 3,
                            Grade = 7,
                            Semester = "Fall",
                            StudentId = 4L,
                            Year = 2024
                        },
                        new
                        {
                            Id = 5L,
                            CourseId = 4,
                            Grade = 9,
                            Semester = "Spring",
                            StudentId = 5L,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("WorkShop1.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AcquiredCredits")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CurrentSemester = 3,
                            EducationLevel = "Undergraduate",
                            FirstName = "Marko",
                            LastName = "Jovanov",
                            StudentId = "201001"
                        },
                        new
                        {
                            Id = 2L,
                            CurrentSemester = 5,
                            EducationLevel = "Undergraduate",
                            FirstName = "Elena",
                            LastName = "Stojanovska",
                            StudentId = "201002"
                        },
                        new
                        {
                            Id = 3L,
                            CurrentSemester = 7,
                            EducationLevel = "Undergraduate",
                            FirstName = "Stefan",
                            LastName = "Nikolov",
                            StudentId = "201003"
                        },
                        new
                        {
                            Id = 4L,
                            CurrentSemester = 1,
                            EducationLevel = "Undergraduate",
                            FirstName = "Ivana",
                            LastName = "Trajkovska",
                            StudentId = "201004"
                        },
                        new
                        {
                            Id = 5L,
                            CurrentSemester = 6,
                            EducationLevel = "Undergraduate",
                            FirstName = "Bojan",
                            LastName = "Ristov",
                            StudentId = "201005"
                        });
                });

            modelBuilder.Entity("WorkShop1.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicRank")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicRank = "Professor",
                            Degree = "PhD",
                            FirstName = "Ivan",
                            LastName = "Petrovski",
                            OfficeNumber = "A101"
                        },
                        new
                        {
                            Id = 2,
                            AcademicRank = "Associate Professor",
                            Degree = "PhD",
                            FirstName = "Marija",
                            LastName = "Stojanova",
                            OfficeNumber = "A102"
                        },
                        new
                        {
                            Id = 3,
                            AcademicRank = "Assistant",
                            Degree = "MSc",
                            FirstName = "Petar",
                            LastName = "Kostov",
                            OfficeNumber = "B201"
                        },
                        new
                        {
                            Id = 4,
                            AcademicRank = "Professor",
                            Degree = "PhD",
                            FirstName = "Ana",
                            LastName = "Dimitrova",
                            OfficeNumber = "B202"
                        },
                        new
                        {
                            Id = 5,
                            AcademicRank = "Assistant",
                            Degree = "MSc",
                            FirstName = "Nikola",
                            LastName = "Iliev",
                            OfficeNumber = "C301"
                        });
                });

            modelBuilder.Entity("WorkShop1.Models.Course", b =>
                {
                    b.HasOne("WorkShop1.Models.Teacher", "FirstTeacher")
                        .WithMany("FirstTeacherCourses")
                        .HasForeignKey("FirstTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkShop1.Models.Teacher", "SecondTeacher")
                        .WithMany("SecondTeacherCourses")
                        .HasForeignKey("SecondTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstTeacher");

                    b.Navigation("SecondTeacher");
                });

            modelBuilder.Entity("WorkShop1.Models.Enrollment", b =>
                {
                    b.HasOne("WorkShop1.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkShop1.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WorkShop1.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("WorkShop1.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("WorkShop1.Models.Teacher", b =>
                {
                    b.Navigation("FirstTeacherCourses");

                    b.Navigation("SecondTeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
